import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Garbage App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
